{
 "title": "Sustainability Dashboard - Switch PoE Power",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SOURCE",
    "query": "show tag values with key = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/state/temperature",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 27, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts (W)" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data",
     "select": [
      [
       { "params": [ "poe_module/available_power" ], "type": "field" },
       { "params": [ "Available Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_module/used_power" ], "type": "field" },
       { "params": [ "Used Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/consumed_poe_power" ], "type": "field" },
       { "params": [ "Consumed PoE Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_stack/unused_power" ], "type": "field" },
       { "params": [ "Unused Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/power_budget" ], "type": "field" },
       { "params": [ "Power Budget" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Sustainability Dashboard - PoE Switch Power",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data",
     "select": [
      [
       { "params": [ "poe_switch/power_allocated" ], "type": "field" },
       { "params": [ "Power Allocated" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/power_budget" ], "type": "field" },
       { "params": [ "Power Budget" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/available_power" ], "type": "field" },
       { "params": [ "Available Power" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "poe_switch/consumed_system_power"
        ],
        "type": "field"
       },
       { "params": [ "Consumed System Power" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "poe_switch/consumed_switch_power"
        ],
        "type": "field"
       },
       { "params": [ "Consumed Switch Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/consumed_poe_power" ], "type": "field" },
       { "params": [ "Consumed PoE Power" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "PoE Power",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data",
     "select": [
      [
       { "params": [ "poe_switch/available_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Available Power" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "poe_switch/consumed_system_power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Consumed System Power" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "poe_switch/consumed_switch_power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Consumed Switch Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/consumed_poe_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Consumed PoE Power" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/power_allocated" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power Allocated" ], "type": "alias" }
      ],
      [
       { "params": [ "poe_switch/power_budget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power Budget" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "PoE Interface",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "*" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
     "select": [
      [
       { "params": [ "intf_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "pd_class" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "power_to_pd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "device_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Total PoE Ports",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data",
     "select": [
      [
       { "params": [ "poe_module/used_ports" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  }
 ]
}